// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/catalog.ts
var catalogProducts = [
  { id: "1", name: "Pa\xF1ales Premium Reci\xE9n Nacido", price: 45e3, originalPrice: 55e3, category: "Pa\xF1ales", categoryId: "panales", description: "Pa\xF1ales ultra suaves con tecnolog\xEDa absorbente de \xFAltima generaci\xF3n. Perfectos para la piel delicada de tu reci\xE9n nacido.", rating: 5, stock: 25, isNew: true, discount: 18, brand: "Premium Baby", size: "Talla RN (hasta 4kg)", age: "0-3 meses", features: ["Ultra absorbente", "Hipoalerg\xE9nico", "Indicador de humedad", "Ajuste anat\xF3mico", "Suavidad premium"] },
  { id: "2", name: "Leche de F\xF3rmula Premium Etapa 1", price: 85e3, originalPrice: 95e3, category: "Alimentaci\xF3n", categoryId: "alimentacion", description: "Leche de f\xF3rmula enriquecida con DHA y vitaminas esenciales para el desarrollo \xF3ptimo de tu beb\xE9.", rating: 5, stock: 15, isNew: true, discount: 11, brand: "Premium Baby", size: "900g", age: "0-6 meses", features: ["Enriquecida con DHA", "Vitaminas esenciales", "F\xE1cil digesti\xF3n", "Desarrollo cerebral"] },
  { id: "3", name: "Set de Juguetes Sensoriales", price: 68e3, originalPrice: 85e3, category: "Jugueter\xEDa", categoryId: "jugueteria", description: "Set completo de peluches y sonajeros para estimular los sentidos de tu beb\xE9 desde los primeros meses.", rating: 5, stock: 20, discount: 20, brand: "Fun Baby", age: "0-12 meses", features: ["Colores estimulantes", "Texturas variadas", "Materiales seguros", "Libre de BPA"] },
  { id: "4", name: "Coche de Paseo Premium", price: 45e4, originalPrice: 52e4, category: "Paseadores", categoryId: "paseadores", description: "Coche de paseo elegante y funcional con sistema plegable, suspensi\xF3n y m\xFAltiples posiciones de reclinado.", rating: 5, stock: 8, discount: 13, brand: "Baby Comfort", age: "0-36 meses", features: ["Sistema plegable", "Suspensi\xF3n suave", "M\xFAltiples posiciones", "Capota expandible", "Canasta amplia"] },
  { id: "5", name: "Set Biberones y Chupos Anti-C\xF3licos", price: 75e3, category: "Teteros y Chupos", categoryId: "teteros", description: "Set completo de 3 biberones con tetinas anti-c\xF3licos y 3 chupos ortod\xF3nticos para el bienestar de tu beb\xE9.", rating: 5, stock: 30, isNew: true, brand: "FlowEasy", age: "0-12 meses", features: ["Sistema anti-c\xF3licos", "Tetina anat\xF3mica", "Libre de BPA", "F\xE1cil limpieza"] },
  { id: "6", name: "Kit de Higiene y Cuidado Personal", price: 95e3, originalPrice: 115e3, category: "Cuidado Personal", categoryId: "cuidado", description: "Kit completo con shampoo, loci\xF3n, crema y gel de ba\xF1o con ingredientes naturales para el cuidado diario.", rating: 5, stock: 25, discount: 17, brand: "Pure Baby", age: "0-24 meses", features: ["Ingredientes naturales", "Sin l\xE1grimas", "Dermatol\xF3gicamente probado", "Aromas suaves"] },
  { id: "7", name: "Toallitas H\xFAmedas Sensitive x80", price: 18e3, category: "Cuidado Personal", categoryId: "cuidado", description: "Toallitas h\xFAmedas para piel sensible con loci\xF3n humectante, sin alcohol ni fragancias fuertes.", rating: 5, stock: 50, brand: "Soft Care", size: "Pack x80", age: "0-24 meses", features: ["Piel sensible", "Sin alcohol", "Con loci\xF3n", "PH balanceado"] },
  { id: "8", name: "Manta Suave de Fleece Premium", price: 48e3, originalPrice: 6e4, category: "Ropa y Textiles", categoryId: "ropa", description: "Manta ultra suave de fleece premium, perfecta para mantener a tu beb\xE9 abrigado y c\xF3modo.", rating: 5, stock: 12, discount: 20, brand: "Cozy Dreams", size: "100x120cm", age: "0-24 meses", features: ["Fleece premium", "Ultra suave", "Lavable a m\xE1quina", "Hipoalerg\xE9nica"] },
  { id: "9", name: "Set de Mordedores Refrigerantes", price: 35e3, category: "Accesorios", categoryId: "accesorios", description: "Set de mordedores coloridos con diferentes texturas para aliviar las molestias de la dentici\xF3n.", rating: 5, stock: 25, isNew: true, brand: "Teething Relief", age: "3-12 meses", features: ["M\xFAltiples texturas", "Se puede refrigerar", "F\xE1cil agarre", "Libre de BPA"] },
  { id: "10", name: "M\xF3vil Musical para Cuna", price: 89e3, originalPrice: 11e4, category: "Accesorios", categoryId: "accesorios", description: "M\xF3vil musical con melod\xEDas suaves y figuras en colores pastel para estimular y relajar a tu beb\xE9.", rating: 5, stock: 10, discount: 19, brand: "Dream Baby", age: "0-12 meses", features: ["Melod\xEDas relajantes", "Rotaci\xF3n autom\xE1tica", "Colores suaves", "F\xE1cil instalaci\xF3n"] },
  { id: "11", name: "Body de Algod\xF3n Org\xE1nico", price: 28e3, category: "Ropa y Textiles", categoryId: "ropa", description: "Body de algod\xF3n org\xE1nico 100% certificado, suave y c\xF3modo para la piel delicada de tu beb\xE9.", rating: 5, stock: 35, brand: "Organic Baby", size: "Talla 0-3M", age: "0-3 meses", features: ["Algod\xF3n org\xE1nico", "Certificado GOTS", "Botones de presi\xF3n", "Suave al tacto"] },
  { id: "12", name: "Crema Protectora Antipa\xF1alitis", price: 32e3, originalPrice: 4e4, category: "Cuidado Personal", categoryId: "cuidado", description: "Crema con \xF3xido de zinc que previene y alivia las rozaduras del pa\xF1al de forma efectiva.", rating: 5, stock: 40, discount: 20, brand: "Protect Baby", size: "100g", age: "0-24 meses", features: ["Con \xF3xido de zinc", "Acci\xF3n calmante", "Barrera protectora", "Hipoalerg\xE9nico"] },
  { id: "13", name: "Ba\xF1era Ergon\xF3mica con Accesorios", price: 125e3, originalPrice: 15e4, category: "Accesorios", categoryId: "accesorios", description: "Ba\xF1era ergon\xF3mica con soporte antideslizante y accesorios para un ba\xF1o seguro y divertido.", rating: 5, stock: 8, discount: 17, isNew: true, brand: "Bath Baby", age: "0-24 meses", features: ["Dise\xF1o ergon\xF3mico", "Base antideslizante", "Con accesorios", "F\xE1cil de limpiar"] },
  { id: "14", name: "Silla de Comer Baby Premium", price: 189e3, originalPrice: 22e4, category: "Montables", categoryId: "montables", description: "Silla de comer con dise\xF1o ergon\xF3mico, bandeja extra\xEDble y altura ajustable. Perfecta para la hora de las comidas.", rating: 5, stock: 6, discount: 14, brand: "Baby Care", age: "6-36 meses", features: ["Bandeja extra\xEDble", "Altura ajustable", "F\xE1cil de limpiar", "Base estable", "Colores vibrantes"] },
  { id: "15", name: "Caminador Musical Interactivo", price: 165e3, category: "Montables", categoryId: "montables", description: "Caminador con juguetes interactivos, m\xFAsica y luces. Ayuda al desarrollo motor del beb\xE9 de forma segura y divertida.", rating: 5, stock: 4, isNew: true, brand: "Fun Steps", age: "6-18 meses", features: ["Juguetes interactivos", "M\xFAsica y luces", "Base antivuelco", "Altura regulable", "Estimula el desarrollo motor"] },
  { id: "16", name: "Carro El\xE9ctrico Montable Deportivo", price: 42e4, originalPrice: 5e5, category: "Montables", categoryId: "montables", description: "Carro montable el\xE9ctrico con dise\xF1o deportivo, control remoto para padres y luces LED. Diversi\xF3n asegurada para los peque\xF1os.", rating: 5, stock: 2, discount: 16, isNew: true, brand: "Sport Kids", age: "2-5 a\xF1os", features: ["Motor el\xE9ctrico", "Control remoto parental", "Luces LED", "Dise\xF1o deportivo", "Bater\xEDa recargable", "Velocidad ajustable"] }
];
var getCatalogProductById = (id) => catalogProducts.find((p) => p.id === id);

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List products from the Pa\xF1alera La Elegancia del Baby catalog. Optionally filter by category id (panales, alimentacion, jugueteria, paseadores, teteros, cuidado, ropa, accesorios, montables) and limit the number of results.",
  inputSchema: {
    categoryId: z.string().optional().describe("Optional category id to filter by (e.g. 'panales')."),
    limit: z.number().int().positive().optional().describe("Optional max number of products to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoryId, limit }) => {
    let items = catalogProducts;
    if (categoryId) {
      items = items.filter((p) => p.categoryId === categoryId);
    }
    if (limit) items = items.slice(0, limit);
    const summary = items.map((p) => ({
      id: p.id,
      name: p.name,
      price: p.price,
      originalPrice: p.originalPrice,
      category: p.category,
      categoryId: p.categoryId,
      brand: p.brand,
      age: p.age,
      size: p.size,
      stock: p.stock,
      isNew: p.isNew ?? false,
      discount: p.discount
    }));
    return {
      content: [
        {
          type: "text",
          text: `Se encontraron ${summary.length} producto(s).

${JSON.stringify(summary, null, 2)}`
        }
      ],
      structuredContent: { count: summary.length, products: summary }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Get full details of a single product from the Pa\xF1alera La Elegancia del Baby catalog by its id, including description, features, brand, price, discount, stock and recommended age.",
  inputSchema: {
    id: z2.string().min(1).describe("Product id (e.g. '1', '2', ...).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const product = getCatalogProductById(id);
    if (!product) {
      return {
        content: [
          { type: "text", text: `No se encontr\xF3 un producto con id '${id}'.` }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_products_default = defineTool3({
  name: "search_products",
  title: "Search products",
  description: "Full-text search across the Pa\xF1alera La Elegancia del Baby catalog. Matches product name, description, brand, category, features, size and recommended age.",
  inputSchema: {
    query: z3.string().min(1).describe("Search text, e.g. 'pa\xF1ales reci\xE9n nacido', 'shampoo', 'caminador'."),
    limit: z3.number().int().positive().optional().describe("Max results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase();
    let items = catalogProducts.filter((p) => {
      const haystack = [
        p.name,
        p.description,
        p.brand,
        p.category,
        p.categoryId,
        p.size ?? "",
        p.age ?? "",
        p.features.join(" ")
      ].join(" ").toLowerCase();
      return haystack.includes(q);
    });
    if (limit) items = items.slice(0, limit);
    const summary = items.map((p) => ({
      id: p.id,
      name: p.name,
      price: p.price,
      category: p.category,
      brand: p.brand,
      age: p.age,
      stock: p.stock
    }));
    return {
      content: [
        {
          type: "text",
          text: `Se encontraron ${summary.length} resultado(s) para "${query}".

${JSON.stringify(summary, null, 2)}`
        }
      ],
      structuredContent: { query, count: summary.length, products: summary }
    };
  }
});

// src/lib/mcp/tools/list-branches.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var BRANCHES = [
  {
    id: "neiva",
    name: "Neiva - Sede Principal",
    city: "Neiva",
    department: "Huila",
    hours: {
      mondayToSaturday: "8:30am - 8:30pm",
      sundaysAndHolidays: "9:00am - 2:00pm"
    }
  },
  {
    id: "san-mateo-soacha",
    name: "San Mateo - Soacha",
    city: "Soacha",
    department: "Cundinamarca",
    hours: {
      mondayToSaturday: "8:30am - 8:30pm",
      sundaysAndHolidays: "9:00am - 8:00pm"
    }
  },
  {
    id: "la-plata",
    name: "La Plata",
    city: "La Plata",
    department: "Huila",
    hours: {
      mondayToSaturday: "8:00am - 7:00pm",
      sundaysAndHolidays: "8:00am - 4:00pm"
    }
  }
];
var list_branches_default = defineTool4({
  name: "list_branches",
  title: "List branches",
  description: "List all Pa\xF1alera La Elegancia del Baby physical branches with their city, department and opening hours (weekday and Sunday/holiday schedules).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `La Elegancia del Baby tiene ${BRANCHES.length} sucursales.

${JSON.stringify(BRANCHES, null, 2)}`
      }
    ],
    structuredContent: { count: BRANCHES.length, branches: BRANCHES }
  })
});

// src/lib/mcp/tools/business-info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var BUSINESS_INFO = {
  name: "Pa\xF1alera La Elegancia del Baby",
  slogan: "Todo para tu beb\xE9",
  description: "Cadena de pa\xF1aler\xEDas en Colombia especializada en productos para beb\xE9s: pa\xF1ales, leches formuladas, jugueter\xEDa, montables, paseadores, teteros y chupos, ropa, accesorios y productos de higiene.",
  contact: {
    whatsapp: "+57 320 969 4966",
    whatsappLink: "https://wa.me/573209694966"
  },
  paymentMethods: ["Efectivo", "Visa", "Mastercard", "PSE", "Efecty", "Nequi", "Daviplata"],
  socialMedia: {
    facebook: "https://www.facebook.com/p/Pa\xF1alera-Elegancia-Del-BABY-NEIVA-100092431112023/",
    instagram: "https://www.instagram.com/eleganciadelbaby2009/",
    tiktok: "https://www.tiktok.com/@eleganciadelbaby"
  },
  branches: 3,
  productCategories: [
    "Pa\xF1ales",
    "Alimentaci\xF3n (leches formuladas, teteros, chupos)",
    "Jugueter\xEDa",
    "Montables",
    "Paseadores y caminadores",
    "Cuidado personal e higiene",
    "Ropa y textiles",
    "Accesorios (chupetes, mordedores, cobijas)"
  ],
  shipping: {
    domestic: "Env\xEDos a todo Colombia",
    pickup: "Recogida en tienda gratis en cualquiera de las 3 sucursales",
    freeShippingThreshold: "Env\xEDo gratis en compras seleccionadas por zona"
  }
};
var business_info_default = defineTool5({
  name: "get_business_info",
  title: "Get business info",
  description: "Get general information about Pa\xF1alera La Elegancia del Baby: contact (WhatsApp), payment methods, social media, shipping options and product categories.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(BUSINESS_INFO, null, 2) }],
    structuredContent: { info: BUSINESS_INFO }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "elegancia-del-baby-mcp",
  title: "Pa\xF1alera La Elegancia del Baby",
  version: "0.1.0",
  instructions: "Herramientas p\xFAblicas de la Pa\xF1alera La Elegancia del Baby. Usa `list_products` y `search_products` para consultar el cat\xE1logo, `get_product` para detalles de un producto por id, `list_branches` para ver las 3 sucursales (Neiva, San Mateo-Soacha, La Plata) con horarios, y `get_business_info` para m\xE9todos de pago, WhatsApp y redes sociales.",
  tools: [list_products_default, get_product_default, search_products_default, list_branches_default, business_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
